# -*- coding: utf-8 -*-
"""Forward Chaining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Prm9J4BjFZPqqqEK7acn5U70j7zWsr1F
"""

def forward_chaining(facts, rules):
  inferred = set(facts)
  changed = True
  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred

facts = {"has_feathers", "has_beak", "carnivore"}
rules = [
    {"if": {"has_feathers", "has_beak"}, "then": "is_bird"},
    {"if": {"lays_eggs", "is_bird"}, "then": "is_chicken"},
    {"if": {"cannot_fly", "is_bird"}, "then": "is_penguin"},
    {"if": {"carnivore", "is_bird"}, "then": "is_eagle"}
]

result = forward_chaining(facts, rules)
print("inferred facts:", result)

def forward_chaining(facts, rules):
  inferred = set(facts)
  changed = True
  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred

facts = {"has_wheels, has_engine, has_four_wheels"}
rules = [
    {"if": {"has_wheels", "has_engine"}, "then": "is_vehicle"},
    {"if": {"is_vehicle", "has_two_wheels"}, "then": "is_motorcycle"},
    {"if": {"is_vehicle", "has_four_wheels"}, "then": "is_car"},
]

result = forward_chaining(facts, rules)
print("inferred facts:", result)