# -*- coding: utf-8 -*-
"""Sistem Pakar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLQoYFXA6_XE_LOWd3e4V_t-UHSRg_-Q
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):
    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True))
    def flu(self):
        print("Diagnosis: You may have the flu.")

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True))
    def pneumonia(self):
        print("Diagnosis: You may have pneumonia.")

    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False))
    def cold(self):
        print("Diagnosis: You may have a common cold.")

    @Rule(Fact(sore_throat=True) & Fact(fever=True))
    def throat_infection(self):
        print("Diagnosis: You may have a throat infection.")

    @Rule(Fact(cough=False) & Fact(fever=False) & Fact(fatigue=False))
    def healthy(self):
        print("Diagnosis: You seem to be healthy.")

    @Rule(Fact(stomachache=True) & Fact(nausea=True) & Fact(diarrhea=True))
    def food_poisoning(self):
        print("Diagnosis: You may have food poisoning.")

    # Tambahan penyakit:
    @Rule(Fact(headache=True) & Fact(nausea=True) & Fact(sensitivity_to_light=True))
    def migraine(self):
        print("Diagnosis: You may have a migraine.")

    @Rule(Fact(fever=True) & Fact(headache=True) & Fact(joint_pain=True))
    def dengue(self):
        print("Diagnosis: You may have dengue fever.")

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(loss_of_smell=True))
    def covid(self):
        print("Diagnosis: You may have COVID-19.")

    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(itchy_eyes=True))
    def allergy(self):
        print("Diagnosis: You may have an allergy.")


def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "cough": ask_question("Do you have a cough?"),
        "fever": ask_question("Do you have a fever?"),
        "fatigue": ask_question("Do you feel fatigued?"),
        "breathing_difficulty": ask_question("Do you have breathing difficulties?"),
        "sneezing": ask_question("Are you sneezing?"),
        "runny_nose": ask_question("Do you have a runny nose?"),
        "sore_throat": ask_question("Do you have a sore throat?"),
        "stomachache": ask_question("Do you have a stomachache?"),
        "nausea": ask_question("Do you feel nauseous?"),
        "diarrhea": ask_question("Do you have diarrhea?"),
        # Gejala tambahan
        "headache": ask_question("Do you have a headache?"),
        "sensitivity_to_light": ask_question("Are you sensitive to light?"),
        "joint_pain": ask_question("Do you have joint pain?"),
        "loss_of_smell": ask_question("Have you lost your sense of smell?"),
        "itchy_eyes": ask_question("Do you have itchy eyes?")
    }

# Menjalankan sistem pakar
if __name__ == "__main__":
    symptoms = get_input()
    engine = Diagnosis()
    engine.reset()  # Reset the knowledge engine

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))  # Declare facts
    engine.run()  # Run the inference engine

from experta import *

class SistemPakarMedis(KnowledgeEngine):

    @Rule(Fact(demam=True) & Fact(batuk=True))
    def flu(self):
        print("Diagnosis: Flu.")

    @Rule(Fact(sakit_tenggorokan=True) & Fact(demam=True))
    def throat_infection(self):
        print("Diagnosis: Radang Tenggorokan.")

    @Rule(Fact(nyeri_otot=True) & Fact(nyeri_perut=True))
    def hernia(self):
        print("Diagnosis: Hernia. Innalillahi.")

    @Rule(Fact(kanker=True) & Fact(tbc=True) & Fact(tipus=True) & Fact(tumor=True))
    def mati(self):
        print("Diagnosis: Anda mengalami kondisi serius. Segera hubungi tenaga medis!")

    @Rule(Fact(sakit_kepala=True) & Fact(mual=True) & Fact(sensitif_cahaya=True))
    def migrain(self):
        print("Diagnosis: Anda mungkin mengalami migrain.")

    @Rule(Fact(demam=True) & Fact(sakit_kepala=True) & Fact(nyeri_sendi=True))
    def dbd(self):
        print("Diagnosis: Kemungkinan Anda terkena Demam Berdarah (DBD). Segera periksa ke dokter.")

    @Rule(Fact(demam=True) & Fact(batuk=True) & Fact(kehilangan_penciuman=True))
    def covid(self):
        print("Diagnosis: Gejala mengarah pada COVID-19. Lakukan tes dan isolasi mandiri.")

    @Rule(Fact(bersin=True) & Fact(hidung_berair=True) & Fact(mata_gatal=True))
    def alergi(self):
        print("Diagnosis: Anda mungkin mengalami alergi.")

# Contoh menjalankan sistem dengan gejala berat
if __name__ == "__main__":
    engine = SistemPakarMedis()
    engine.reset()

    # Silakan ubah fakta sesuai gejala yang ingin diuji:
    engine.declare(Fact(demam=True))
    engine.declare(Fact(batuk=True))
    engine.declare(Fact(kehilangan_penciuman=True))
    engine.declare(Fact(sakit_kepala=True))
    engine.declare(Fact(mual=True))
    engine.declare(Fact(sensitif_cahaya=True))
    engine.declare(Fact(bersin=True))
    engine.declare(Fact(hidung_berair=True))
    engine.declare(Fact(mata_gatal=True))

    engine.run()